### ISSUE TITLE
Transform function not work well with umbrella project

### ISSUE THREAD

**Issue by sawater** [bitwalker/conform#115]
`mix conform.effective` is fine, while error occurs when `MIX_ENV=prod mix release --name=combined --verbose` merging schema files.
```
==> conform: loading schema
==> conform: merging config app_one
==> conform: merging config app_two
==> conform: merging config master_app
==> conform: merging schema app_one
==> conform: merging schema app_two
==> conform: merging schema master_app
==> Plugin failed: Invalid schema at line 80: syntax error before: ']'.
```
I have pulled the error code to bitwalker/distillery-umbrella-test#10. May be can help you to do the test.

**Comment by dpehrson** [comment]
I've found this too, depending on what you're doing you need to use a `:` or ``=>` after the name of the key in the transforms list. Whatever character you use, something different will error. `conform.effective` for example errors if you use a `:`.

**Comment by jschniper** [comment]
I've run into this as well. ~2.2 works but 2.3.0 and 2.3.2 both fail. I haven't tried 2.3.1.

**Comment by dpehrson** [comment]
FWIW I have since stopped using confirm and fallen back to using just distillery + `REPLACE_OS_VARS`. I ran into far too many problems trying to get conform to work.

**Comment by bitwalker** [comment]
Just FYI, the issue with `:` vs `=>` sounds like a confusion on how you can represent atom keys in lists (the syntax of which is of course used in the schema since it's an Elixir data structure). You should never be using `=>` in lists (it's invalid syntax) - and if you were defining transforms as a map, that's likely why there was a problem in the first place.
