### ISSUE TITLE
Schema with atoms as default value fails to start an OTP release app

### ISSUE THREAD

**Issue by lachezar** [bitwalker/conform#116]
To reproduce the bug you can do the following:

```
mix phoenix.new bug --no-ecto --no-brunch --no-html
cd bug
# add distillery and conform to the mix.exs
mix deps.get
mix conform.new
mix release.init
# add plugin Conform.ReleasePlugin to rel/config.exs
MIX_ENV=prod mix release --env=prod
_build/prod/rel/bug/bin/bug foreground

[info] Application bug exited: Bug.start(:normal, []) returned an error: shutdown: failed to start child: Bug.Endpoint
    ** (EXIT) bad start spec: invalid mfa: {{:__aliases__, [line: 102], [:Phoenix, :PubSub, :PG2]}, :start_link, [Bug.PubSub, [fastlane: Phoenix.Channel.Server, pool_size: 1, adapter: {:__aliases__, [line: 102], [:Phoenix, :PubSub, :PG2]}, name: {:__aliases__, [line: 94], [:Bug, :PubSub]}]]}
{"Kernel pid terminated",application_controller,"{application_start_failure,bug,{{shutdown,{failed_to_start_child,'Elixir.Bug.Endpoint',{start_spec,{invalid_mfa,{{'__aliases__',[{line,102}],['Phoenix','PubSub','PG2']},start_link,['Elixir.Bug.PubSub',[{fastlane,'Elixir.Phoenix.Channel.Server'},{pool_size,1},{adapter,{'__aliases__',[{line,102}],['Phoenix','PubSub','PG2']}},{name,{'__aliases__',[{line,94}],['Bug','PubSub']}}]]}}}}},{'Elixir.Bug',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,bug,{{shutdown,{failed_to_start_child,'Elixir.Bug.Endpoint',{start_spec,{invalid_mfa,{{'__aliases__',[{line,102}],['Phoenix',

Crash dump is being written to: erl_crash.dump...done

Shutting down..
Node is not running!
```

Commenting out the sections in the schema which have modules as default values mitigates the issue:
```
   # "bug.Elixir.Bug.Endpoint.pubsub.name": [
   #   commented: false,
   #   datatype: :atom,
   #   default: Bug.PubSub,
   #   doc: "Provide documentation for bug.Elixir.Bug.Endpoint.pubsub.name here.",
   #   hidden: false,
   #   to: "bug.Elixir.Bug.Endpoint.pubsub.name"
   # ],
   # "bug.Elixir.Bug.Endpoint.pubsub.adapter": [
   #   commented: false,
   #   datatype: :atom,
   #   default: Phoenix.PubSub.PG2,
   #   doc: "Provide documentation for bug.Elixir.Bug.Endpoint.pubsub.adapter here.",
   #   hidden: false,
   #   to: "bug.Elixir.Bug.Endpoint.pubsub.adapter"
   # ],
```

**Comment by dpehrson** [comment]
Just hit this as well. I've found that a significant amount of configuration properties don't seem to be handled properly with conform. Thankfully most of them don't actually need to be run-time configurable.

Are we doing something wrong?

**Comment by bitwalker** [comment]
Conform can only do so much to generate the config files for you - the idea was to give you a hefty head start, but that some manual intervention would always be required to get things to work the way you want them to.

Conform is intended to have some thought put in up front to build a schema that takes a simple, easy to use form (the .conf) and convert it to the far more complex datastructure required by the application. For simple types, including lists of simple types, as well as keyword lists, you can just use the auto-generated schema, but for things of a more complex nature, you will want to spend time defining types, transforms, etc., so that you take a simple expression, say "1 day", and convert that to some value like a Duration struct, or maybe a tuple like "{1, :day}". It is impossible for Conform to be able to do this for you for custom types like that, partly because rich datatypes can't actually be encoded in the simple language the `.conf` offers.

Over time I will be adding more warnings and informational messages to try and prod people in the right direction with this, so that this doesn't catch people off guard. Unfortunately it hasn't gotten as much love as exrm/distillery by me, because I use it the way I designed it, but didn't spend a great deal of time trying to make sure it worked magic out of the box. I am however hoping to get the UX of this project improved to the point where it's less painful to get started :)

I'm going to take a look at this example though, hopefully tonight or in the morning, and see if this is just something that *should* be working, but isn't, or just something that needs better information produced for the consumer.

**Comment by bitwalker** [comment]
Looks like this is working as of 2.3.3, which I'm about to push.
