### ISSUE TITLE
Enhancement(?): ReleasePlugin should choose .conf filename based on distillery environment, not Mix environment

### ISSUE THREAD

**Issue by dpehrson** [bitwalker/conform#118]
## Scenario

In my setup I have two deployment environments, `staging` and `production`, the both are built using `MIX_ENV=prod`, and their releases differ only in the conform configuration values I would like to bundle (hostnames, security keys/tokens, etc.)

## Expected behavior

Executing `MIX_ENV=prod mix release --env=staging` should utilize `my_app.staging.conf`

## Actual behavior

Executing `MIX_ENV=prod mix release --env=staging` utilizes `my_app.prod.conf`

## Problem

As far as I can tell, there is no way to build environment-specific releases based on config without supporting an entirely different `MIX_ENV`

Is there another way to accomplish what I'm trying to do?

**Comment by bitwalker** [comment]
`MIX_ENV` is really what you want to be using here. Distillery "environments" are profiles for how the release itself is built/packaged, but is not intended to reflect runtime or configuration environment specifics (such as configs). My recommendation here is to define your own environment, e.g. `MIX_ENV=staging`, and ensure the settings in `mix.exs` like `build_embedded`, etc., treat `MIX_ENV=staging` the same as `MIX_ENV=prod`.

If it turns out that there are fundamental problems with that (none that I'm aware of at this time though), then I can look into adapting both Distillery and Conform to "prefer" configs which match the Distillery environment first, and `MIX_ENV` second if no match is found for the Distillery env. I would prefer not to do that though, as it's a bit too much implicit "magic" for my taste, but if it turns out to be more intuitive, it may be worth while.
