### ISSUE TITLE
Generated sys.config is overwritten when running bin/<app_name> ping/console/etc

### ISSUE THREAD

**Issue by aaronrenner** [bitwalker/conform#126]
I'm having an issue where if I start my app using edeliver, the sys.config file does not have the changes from the <app_name>.conf file merged in, but if I manually run `bin/<app_name> start`, the <app_name>.conf changes are merged in successfully. I am using distillery to package my app.

I've been trying to dig through edeliver to see how it's starting the app, and am having trouble seeing if it's starting the app via the `bin/<app_name>` script or if it's using some other method.

Any tips would be greatly apprecated!

**Comment by aaronrenner** [comment]
So it appears that `<release_name>/releases/<version>/<release_name>.sh` is clobbering `<release_name>/var/sys.config` if `<release_name>/sys.config` isn't found (https://github.com/bitwalker/distillery/blob/a895ce0f519f36efb93124c41048c75f82a5a591/priv/templates/boot.eex#L324-L340)

The problem is edeliver runs `<release_name>/releases/<version>/<release_name>.sh` multiple times, and it only runs conform's `<release_name>/releases/<version>/hooks/pre_configure.d/00_conform_pre_configure.sh ` once.

```
<release_name>/releases/<version>/<release_name>.sh ping
<release_name>/releases/<version>/<release_name>.sh start # Correct config is generated
<release_name>/releases/<version>/<release_name>.sh console #sys.config is wiped out
<release_name>/releases/<version>/<release_name>.sh ping #sys.config is wiped out
<release_name>/releases/<version>/<release_name>.sh rpcterms #sys.config is wiped out
```

It looks like every command (ping, console, rpcterms, etc.) clobbers `<release_name>/var/sys.config`, and the conform hooks that generate the correct sys.config are only called when `<release_name>/releases/<version>/<release_name>.sh start` is called. I'm thinking this could possibly be a distillery issue instead of a conform issue.

**Comment by bitwalker** [comment]
Wait, edeliver is invoking the script in `<deploy_dir>/releases/<version>` directly? That would explain *a lot*.

**Comment by aaronrenner** [comment]
I'm not sure edeliver that is actually calling `<deploy_dir>/releases/<version>` directly. I put a lot of log statements in the deploy scripts on the server to figure out what's happening and I'm not sure if another script calls `<deploy_dir>/releases/<version>/<release_name>.sh`.

Here's how to reproduce it without edeliver even being in the picture:

1. `./bin/<app_name> start`
2. Look at `var/sys.config` and see that the conform changes have been merged into this file
3. `./bin/<app_name> ping
4. Look at `var/sys.config` and see that the conform changes are gone.

I think this bug because distillery [overwrites `var/sys.config`](https://github.com/bitwalker/distillery/blob/a895ce0f519f36efb93124c41048c75f82a5a591/priv/templates/boot.eex#L324-L340) on every command, and only calls the pre_configure and pre_start hooks that conform uses on commands like `start`.

**Comment by bitwalker** [comment]
Anyway, to clarify, anytime the boot script is invoked, an internal function `_init_configs` is called. This function is pretty complex, because it will be invoked recursively, and in some cases multiple times (such as during an upgrade/downgrade when the configs need to be unpacked, and then updated). This overwrites `/var/vm.args` and `/var/sys.config` every time, unless the current env's `VMARGS_PATH` and `SYS_CONFIG_PATH` are set to the `/var` path, which happens in `_init_configs` and is there to protect those files when the boot script is invoked recursively (in the case of running the `start` command, as `run_erl` calls the boot script again).

On the other hand, the `pre_configure` hook, used by Conform, but can be used by anything really, is only invoked during certain commands (anything which needs the config to be generated, which is most things, `ping` and the various `rpc*` functions do not though).

So, it seems like the problem here is that `_init_configs` should probably also run the `pre_configure` hooks. I'll need to do some testing

**Comment by bitwalker** [comment]
Yes, you're correct :)

**Comment by bitwalker** [comment]
After another moment of thought, I'll have to be more careful than just running `pre_configure` from `_init_configs`, since at that point the release environment is not fully ready, so hooks would have to be very careful what they do (particularly they would need to avoid running any commands which invoke the boot script again to avoid an infinite loop).

**Comment by bitwalker** [comment]
So I've pushed a fix to Distillery master which addresses this, give it a shot and feel free to reopen this if there is still an issue! I'll be pushing a new release to hex pretty soon.

**Comment by aaronrenner** [comment]
Thank you so much. I'll check it out!

**Comment by aaronrenner** [comment]
Just tested it out with Distillery master and it works great! 🎉

**Comment by bitwalker** [comment]
Great! I'll get that released ASAP
