### ISSUE TITLE
Application configuration not available in Plug 

### ISSUE THREAD

**Issue by ngeraedts** [bitwalker/conform#130]
I'm trying to enable and disable a static route in Plug using a configuration parameter supplied by Conform. The application has the expected behaviour when run directly via Mix, but fails to pick up the right values when the values are parsed by Conform.

I've written a minimal application that reflects the behaviour I'm experiencing in my parent application. Any insight would be appreciated.

https://github.com/ngeraedts/test_plug_static

**Comment by bitwalker** [comment]
Your example project works in 2.4.0 just fine. It looks like there is some kind of problem with 2.2.0 though, can you upgrade?

**Comment by ngeraedts** [comment]
I've updated to 2.4 with the same results. I'm not sure if this is a specifically a Conform issue, or a Plug issue, or an edge case between the two (or I'm doing something horribly out of left field).

When I run the `prod` release, the result of `Application.get_env(:test_plug_static, :static)` in the console is correct, but the logic at [http.ex:5](https://github.com/ngeraedts/test_plug_static/blob/master/lib/http.ex#L5) doesn't seem to reflect the value from Conform. If you try to curl `/static/testfile.txt`, you'll get `not found` indicating to me that the static route was never set up in the first place.

**Comment by bitwalker** [comment]
That code is being run at compile-time, not runtime - in other words it is evaluated when you are building the release, not when you run it.

**Comment by ngeraedts** [comment]
I figured it was the compile/runtime difference. I'm still trying to determine at a glance when each of them occurs. Do you have any insights about how to mimic the behaviour I'm looking for?

That being said, Conform has made the rest of my release configuration a breeze!

**Comment by bitwalker** [comment]
My trick is to look and see if the code is inside a function body - if it's not, it's almost certainly being evaluated when the module body is evaluated, which happens at compile-time. The only exception to this would be if a macro takes a `do` block which contains some code - in those cases it's likely that the block will be evaluated at runtime. In your case, the macro is taking options, but those options aren't quoted (i.e. inside a `do` block), so they are evaluated when the macro is invoked. Hopefully that helps :)

I think I'd need to know a bit more about why you are conditionally enabling/disabling static assets first before I can really give you good advice on how to achieve what you are trying to do here. Can you expand on that a bit?

I'm glad conform has been working out well for you otherwise! Please let me know if you find any rough edges or things missing that you'd like to see and I'll be glad to look into it :)

**Comment by ngeraedts** [comment]
I've taken the release tarball generated by Distillery and repackaged it with an init script into an RPM for the systems team to easily deploy. They like packages and configuration files; sadly, Docker is out of the question for a few months at least. 

The main application provides a JSON API and is configured in production to pull assets from an external URL. These tarballs contain other code (typically python) that is run via `Port.open/2`. 

Occasionally, our developers need to generate new versions of the tarballs in our dev environments. I was hoping to add another endpoint to host these tarballs from a local path when the application is installed in development. 

The alternative would be to configure an external service such as nginx to host the assets. 

Production config:
```
my_app.url_to_assets = <external url>
# master.serve_static = 
```

Development config:
```
my_app.url_to_assets = http://localhost:8000/static
my_app.serve_static = "/opt/my_app/static/"
```

**Comment by ngeraedts** [comment]
And your note about code being inside/outside a function body does help. I'll try to keep that in mind. :)

**Comment by bitwalker** [comment]
Ok, in that case the code you have now is fine, but you won't need to configure the `static` option with Conform, you can remove it from both the `.conf` and the `.schema.exs` - if you know that only in dev you will need the Static plug enabled, then in `config.exs` do the configuration necessary to enable it and configured it as desired. In your `prod.exs` - simply set it to `nil` so that it is disabled. Then when you build the release, just run `MIX_ENV=prod mix release` to build the release with the static plug disabled or `MIX_ENV=dev mix release` to build it with it enabled (`MIX_ENV=dev` is the default of course, but I just want to illustrate the point).

It doesn't sound like the static stuff needs to be configured once the release is built (it's known ahead of time whether the release will use it or not). That makes things a lot easier :)

Let me know if I misunderstood though - or if there is anything you aren't clear on.

**Comment by ngeraedts** [comment]
That approach certainly would work. The main drawback with building two releases is that we'd end up with different RPMs for production and development. I'll have to mull over my options and see what seems to fit best.

Thanks for the discussion and insights.

**Comment by bitwalker** [comment]
The alternative is to work with Plug at a lower level where you can dynamically inject routes into the pipeline - but you sacrifice a lot for that flexibility. Basically you'll need to move away from compile-time configuration for this, and unfortunately there isn't a good way to do that with the Plug.Builder macros.
