### ISSUE TITLE
Failure in ReleaseManager.Plugin.Conform when using rc6

### ISSUE THREAD

**Issue by alco** [bitwalker/conform#55]
I have updated my test project to also use the latest exrm, https://github.com/alco/conformist/commit/1a7ee58744b520a23b7defde1c5d2d3993c158fa.

When I run `mix release` for the first time (or after removing the `_build` directory), it builds the release. When I try to run it for the second time, I get the following error:

```
$ mix release
Building release with MIX_ENV=prod.
==> conform
Unchecked dependencies for environment prod:
* exrm (Hex package)
  the dependency is not locked (run "mix deps.get" to generate "mix.lock" file)
==> Failed to execute before_release hook for Elixir.ReleaseManager.Plugin.Conform!
==> conformist
** (Mix) Can't continue due to errors on dependencies
```

**Comment by bitwalker** [comment]
I pushed a fix for this yesterday, so if you are running conform 1.0.0-rc6, you shouldn't see this error any longer.

@alco Just out of curiosity, and bear with me because this is relevant I promise :P; I moved conform's exrm plugin to conform as part of the 1.x branch, however I found out recently that conform must declare exrm as an optional dependency in order to enforce exrm being compiled first. This in turn is required because I have a conditional wrapping the plugin's module definition, so that if someone wants to use conform without exrm, it won't compile the task. However, apparently optional dependencies don't actually mean optional, and exrm is no fetched as one of conform's deps. The error you got here is actually an artifact of that, though more specifically it was occurring because the `conform.release` task was building itself as an escript with `MIX_ENV=prod`, and if you haven't compiled your project with `MIX_ENV=prod`, then the dependency isn't there.

SO, my question for you, how can this be improved? My one thought is to provide a conform plugin for exrm as a new dependency, thus keeping the two projects completely isolated, but since I'm operating in a bit of a bubble, it'd be nice to hear from someone that's been around awhile on their thoughts. I've decided that today that gets to be you :P

**Comment by alco** [comment]
I'm running rc6. My `mix.lock` from the link above:

```
+  "conform": {:hex, :conform, "1.0.0-rc6"},
...
+  "exrm": {:hex, :exrm, "1.0.0-rc6"},
```

Let me think some more about the situations with plugins, I'll get back to you with more comments.

**Comment by bitwalker** [comment]
I wonder if this is because of `preferred_cli_env: [release: :prod]`? If the setting is taken into account when the `conform` escript is being built, the error would make sense. I'm not super familiar with the details of that setting though, does that sound like what you'd expect to happen?

**Comment by alco** [comment]
Doesn't look like `preferred_cli_env` is relevant.

I don't understand what you mean here
> The error you got here is actually an artifact of that, though more specifically it was occurring because the `conform.release` task was building itself as an escript with `MIX_ENV=prod`, and if you haven't compiled your project with `MIX_ENV=prod`, then the dependency isn't there.

The issues I'm seeing seem to be the reverse of what you're describing. I did another test:

  * removed `preferred_cli_env`
  * removed `_build/dev`
  * tried creating a release again

It succeeds, you can see the full log in this [gist](https://gist.github.com/alco/dede31be07efcba18544).

When I run `mix release` the second time, it complains about all conform's deps:

```
$ mix release
Building release with MIX_ENV=dev.
==> conform
Unchecked dependencies for environment dev:
* exrm (Hex package)
  the dependency is not locked (run "mix deps.get" to generate "mix.lock" file)
* ex_doc (Hex package)
  the dependency is not available, run "mix deps.get"
* earmark (Hex package)
  the dependency is not available, run "mix deps.get"
==> Failed to execute before_release hook for Elixir.ReleaseManager.Plugin.Conform!
==> conformist
** (Mix) Can't continue due to errors on dependencies
```

And indeed, `mix.lock` does not have `ex_doc` and `earmark`, but it does have `exrm` since it's defined in the root project's `mix.exs`. Calling `mix deps.get` doesn't help:

```
$ mix deps.get
Running dependency resolution
All dependencies up to date

$ mix deps | grep ex_doc

$ mix release
Building release with MIX_ENV=dev.
==> conform
Unchecked dependencies for environment dev:
* exrm (Hex package)
  the dependency is not locked (run "mix deps.get" to generate "mix.lock" file)
* ex_doc (Hex package)
  the dependency is not available, run "mix deps.get"
* earmark (Hex package)
  the dependency is not available, run "mix deps.get"
==> Failed to execute before_release hook for Elixir.ReleaseManager.Plugin.Conform!
==> conformist
** (Mix) Can't continue due to errors on dependencies
```

If I remove `_build/dev`, it works again.

I'm running Elixir 1.1.1 and I don't yet have a theory as to why mix doesn't fetch conform's dev dependencies.

**Comment by bitwalker** [comment]
Well that's new, shit. Conform is being pulled in as a hex package here correct? What happens if you make it a git dependency instead? Does it work then?

**Comment by mpahrens** [comment]
I am experiencing the same problem as a git dependency with:
     { :conform, git: "https://github.com/bitwalker/conform", tag: "1.0.0-rc6"}
and
     {:exrm, "~> 1.0.0-rc5", [hex: :exrm, optional: true]},
Thanks!

**Comment by bitwalker** [comment]
This is so strange. For some reason, mix isn't fetching ex_doc or earmark, but it is fetching neotoma. I have no idea how this could happen. I'll keep looking.

**Comment by bitwalker** [comment]
Ok, I very clearly broke something in a recent commit, so I'll walk back and figure out what it was exactly. Sorry everyone :(

**Comment by bitwalker** [comment]
Ok, so here's the deal:

Pulling the conform plugin into conform itself required some hackery that simply was causing more problems than it was worth. So instead, I've updated conform so that it is standalone entirely, and the conform plugin for exrm is now available via Hex as `conform_exrm`. The project can be found [here](https://github.com/bitwalker/conform_exrm) and covers how to use it as a dependency, but the gist is this:

```elixir
defp deps do
 [{:exrm, "~> 1.0.0-rc7", override: true},
  {:conform, "~> 1.0.0-rc7", override: true},
  {:conform_exrm, "~> 0.1"}]
end
```

I've done some testing and this works as expected. Any feedback you have is greatly appreciated!

**Comment by alco** [comment]
@bitwalker In order to make `conform_exrm` work, it also has to be included in the list of applications of the parent project. I'm not a fan of that because it is a build dependency, not a run-time one.

Now, using `exrm` rc7, `conform` rc7, and `conform_exrm` 0.1.0, I can get the release to build. But it spews warning about conform every second time:

```
$ mix release
Building release with MIX_ENV=prod.
==> conform
Compiled src/conf_parse.erl
lib/conform/schema.ex:1: warning: redefining module Conform.Schema
Compiled lib/conform/schema/transform.ex
Compiled lib/conform/sysconfig.ex
Compiled lib/conform/schema/validator.ex
Compiled lib/conform/schema/mapping.ex
Compiled lib/conform.ex
Compiled lib/conform/type.ex
lib/mix/tasks/conform.archive.ex:1: warning: redefining module Mix.Tasks.Conform.Archive
Compiled lib/conform/types/enum.ex
lib/mix/tasks/conform.configure.ex:1: warning: redefining module Mix.Tasks.Conform.Configure
Compiled lib/conform/validators/range_validator.ex
Compiled lib/conform/parse.ex
lib/mix/tasks/conform.release.ex:1: warning: redefining module Mix.Tasks.Conform.Release
lib/mix/tasks/conform.new.ex:1: warning: redefining module Mix.Tasks.Conform.New
lib/mix/tasks/conform.effective.ex:1: warning: redefining module Mix.Tasks.Conform.Effective
Compiled lib/mix/tasks/conform.archive.ex
Compiled lib/conform/conf.ex
Compiled lib/mix/tasks/conform.release.ex
Compiled lib/conform/utils/utils.ex
Compiled lib/conform/utils/code.ex
Compiled lib/mix/tasks/conform.configure.ex
Compiled lib/mix/tasks/conform.new.ex
Compiled lib/mix/tasks/conform.effective.ex
Compiled lib/conform/schema.ex
Compiled lib/conform/translate.ex
Generated conform app
Generated escript conform with MIX_ENV=prod
==> The release for conformist-0.0.1 is ready!
==> You can boot a console running your release with `$ rel/conformist/bin/conformist console`

$ mix release
==> conform
Compiled src/conf_parse.erl
Compiled lib/conform/schema/transform.ex
Compiled lib/conform/schema/validator.ex
Compiled lib/conform/sysconfig.ex
Compiled lib/conform/schema/mapping.ex
Compiled lib/conform/type.ex
Compiled lib/conform.ex
Compiled lib/conform/types/enum.ex
Compiled lib/conform/validators/range_validator.ex
Compiled lib/conform/parse.ex
Compiled lib/mix/tasks/conform.archive.ex
Compiled lib/mix/tasks/conform.release.ex
Compiled lib/conform/conf.ex
Compiled lib/conform/utils/utils.ex
Compiled lib/conform/utils/code.ex
Compiled lib/mix/tasks/conform.configure.ex
Compiled lib/mix/tasks/conform.new.ex
Compiled lib/mix/tasks/conform.effective.ex
Compiled lib/conform/schema.ex
Compiled lib/conform/translate.ex
Generated conform app
Building release with MIX_ENV=prod.
==> conform
Generated escript conform with MIX_ENV=prod
==> The release for conformist-0.0.1 is ready!
==> You can boot a console running your release with `$ rel/conformist/bin/conformist console`

$ mix release
Building release with MIX_ENV=prod.
==> conform
Compiled src/conf_parse.erl
lib/conform/schema.ex:1: warning: redefining module Conform.Schema
Compiled lib/conform/schema/transform.ex
Compiled lib/conform/schema/validator.ex
Compiled lib/conform/sysconfig.ex
Compiled lib/conform/schema/mapping.ex
Compiled lib/conform/type.ex
Compiled lib/conform.ex
Compiled lib/conform/validators/range_validator.ex
Compiled lib/conform/types/enum.ex
lib/mix/tasks/conform.archive.ex:1: warning: redefining module Mix.Tasks.Conform.Archive
lib/mix/tasks/conform.configure.ex:1: warning: redefining module Mix.Tasks.Conform.Configure
Compiled lib/conform/parse.ex
lib/mix/tasks/conform.new.ex:1: warning: redefining module Mix.Tasks.Conform.New
lib/mix/tasks/conform.effective.ex:1: warning: redefining module Mix.Tasks.Conform.Effective
lib/mix/tasks/conform.release.ex:1: warning: redefining module Mix.Tasks.Conform.Release
Compiled lib/mix/tasks/conform.archive.ex
Compiled lib/conform/conf.ex
Compiled lib/mix/tasks/conform.release.ex
Compiled lib/conform/utils/utils.ex
Compiled lib/mix/tasks/conform.configure.ex
Compiled lib/conform/utils/code.ex
Compiled lib/mix/tasks/conform.new.ex
Compiled lib/mix/tasks/conform.effective.ex
Compiled lib/conform/schema.ex
Compiled lib/conform/translate.ex
Generated conform app
Generated escript conform with MIX_ENV=prod
==> The release for conformist-0.0.1 is ready!
==> You can boot a console running your release with `$ rel/conformist/bin/conformist console`
```

I remember hearing of a similar recompilation issue some time ago, however, I'm not sure it was related to exrm.

**Comment by alco** [comment]
@bitwalker are you completely against merging `conform_exrm` back into `exrm` itself? That would solve  the problem with having to include `conform_exrm` in the list of applications. And if `exrm` checks if `conform`'s modules are available before doing anything with it, that would still allow people to opt out from using `conform`.

**Comment by bitwalker** [comment]
@alco Why do you have to include it in the list of applications? There should be no such requirement.

I'm not totally against merging the plugin back into exrm, however I do have a couple of problems with it:

- I would like to figure out what the model for a shared plugin for exrm looks like, which is effectively what conform_exrm should be. Conform in and of itself should be able to live independently of exrm and vice versa. If I can't get it to work, what needs to happen to come up with a good model for such plugins? Is it something that simply isn't a good fit?
- Placing the plugin back in exrm means that exrm must depend on conform. This means that anyone who wants to use exrm is getting conform as well, regardless of whether they use it. Is this really a big problem? Not necessarily, but it is annoying, and I'm sure I'll hear about it.
- One of the reasons I wanted to keep them isolated from each other is so that upgrading exrm doesn't require you to upgrade conform as well (if there are breaking changes in conform). If they are intrinsically linked, then exrm's versioning also has to take into account breaking changes in conform.
- Making changes to conform that also require changes to the plugin, means I must push a new release of exrm each time such changes occur. Keeping those changes close together (plugin living in conform), or isolated (plugin in it's own project), means that changes to exrm remain relevant to all users of exrm, while only users of conform or the conform plugin are affected by changes related to conform.

I'm absolutely wide open to ideas on what the best approach is for all this. Frankly I'd like to decide on an approach and stick with it, but sadly I think there are cons to just about every approach. Finding the least painful option for users is my first priority, but I would like to make maintenance less of a burden so that I can iterate on things faster. Thoughts?

**Comment by alco** [comment]
> @alco Why do you have to include it in the list of applications? There should be no such requirement.

You're right, I forgot about the new `warn_missing` option. It solves this problem.

As for the best way to distribute the plugin, I think making it a separate project works best for providing the ability to push new releases for projects independently of each other.

I just thought that if `conform` is very often used with `exrm`, the latter could have it as an optional dependency. I realize now how that effectively ties the release processes of both projects with each other.

Can we look at what other projects are doing? Take `timex_ecto` plugin, for example. It fulfils a similar role for `timex` and `ecto` as `conform_exrm` does. Has it worked out well as a standalone project.

By the way, why did you declare the dependencies of `conform_exrm` as optional? It shouldn't work without either of them and it certainly depends on particular versions of both projects to be working as expected.

**Comment by bitwalker** [comment]
The reason why the deps even exist in `conform_exrm` (beyond the need to compile the project, but then they could be declared `only: :dev`) is that without them, `conform_exrm` may be compiled before either `exrm` or `conform`, causing compilation to fail. By making them optional (or just present in general), mix will ensure they are compiled first. I haven't tested whether having them as `only: :dev` accomplishes the same thing with less pain when consumed as a hex package though, I'm going to give that a shot.

`timex_ecto` has worked well from what I've heard from users, but I think it probably has the same issue with requiring `override: true` if you have ecto as a direct dependency. During my testing I think I just added timex and timex_ecto, and let timex_ecto pull the ecto dep, but I can't recall exactly. If there are some other examples you can think of though, I'll check them out to see what others are doing.

**Comment by bitwalker** [comment]
@alco Sadly, marking the deps as `only: :dev` doesn't enforce compilation order :(. I don't know how else to make mix compile them in the correct order other than declaring them as direct deps.

**Comment by bitwalker** [comment]
However, it appears marking them as `optional` is what requires the `override: true`. So I'll be pushing 0.2.0 of conform_exrm shortly.

**Comment by bitwalker** [comment]
Done, and tested. It's much much better now. Still have the recompilation problem though.
