### ISSUE TITLE
Transforms docs in README are old/incorrect

### ISSUE THREAD

**Issue by martin-langhoff** [bitwalker/conform#72]
The API has changed for transforms a while ago, this is rather confusing.

The source code has embedded code samples which are closer to reality. The new API format is rather impractical, here is a code snippet for a transform that takes a value of `"format abcde"` and turns it into `{:format, "abcde"}`, useful for `myapp.some_crypto_key = base64 YTM0NZomIzI2OTsmIzM0NTueYQ==`

```
  transforms: [
    "myapp.some_crypto_key": fn confpid ->
        # discard the wrappers, get at the value
        [{_,val}] = Conform.Conf.get(confpid, "myapp.some_crypto_key")
        #IO.puts "encry #{inspect val}"
        [k, v] = String.split(to_string(val))
        k = String.to_atom(k)
        {k, v}
      end
    ],
```

**Comment by bitwalker** [comment]
@martin-langhoff I'll make sure the docs get updated! You mentioned that the new API format is impractical, could you clarify your concerns? Your specific example is not much longer than alternatives I can think of, but has the benefit of scaling to some very complex configuration requirements. Is there a specific issue you would like to see addressed?

**Comment by martin-langhoff** [comment]
Don't worry about my "impractical" complaint, I was wrapping my mind around the new API. Apologies. 

The important part is to get a current example to the README :-) (alternatively, remove the wrong example and point people to unit tests and source instead...).

**Comment by sdball** [comment]
Thanks for this @martin-langhoff! I was just struggling with trying to get transforms to work and even copied the schema from the README entirely into my app to see if I was missing some critical piece. Your example is great 🎉

**Comment by bitwalker** [comment]
Sorry about that, I somehow completely missed updating the README when I released 2.0, nothing worse than bad docs :(

**Comment by sdball** [comment]
No worries! I'll try and take a pass at updating the README. It'll also help me learn the ins and outs of conform. 😄

**Comment by sdball** [comment]
@bitwalker I've got the `myapp.another_val` transform example working. But I'm having a hard time figuring out how to make the lager settings work. It looks like `Conform.Conf.get` needs to pull the actual setting that the variable is going _to_ and not its friendly id. If that's the case I don't quite understand how to translate the previous example for 2.0. I don't see how the transform can add new keys to the effective configuration.

Let me know if I'm missing something, but I think I'll need to rework the schema a bit in order to support that example.

Also in the README now there's some nice extra documentation for `myapp.another_val`: how is that generated? My generated conf file only has the doc line the allowed values from the enum.

**Comment by bitwalker** [comment]
I've gone through and updated the README, and added tests which cover the examples.
